build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
        - uses: actions/checkout@v2 # Checking out the repo

        - name: Build and Publish latest Docker image
          uses: VaultVulp/gp-docker-action@1.1.12
          with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              image-name: modpipe
              dockerfile: Dockerfile_server